CREATE TABLE IF NOT EXISTS `service_requests` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `tracking_code` VARCHAR(50) NOT NULL UNIQUE,
  `user_id` INT UNSIGNED DEFAULT NULL,
  `organization_id` INT UNSIGNED DEFAULT NULL,
  `request_type` ENUM('personal','organization','municipal') NOT NULL DEFAULT 'personal',
  `status` ENUM('new','under_review','contacted','meeting_scheduled','proposal_sent','contracted','in_production','completed','cancelled') NOT NULL DEFAULT 'new',
  `priority` ENUM('normal','high','urgent') NOT NULL DEFAULT 'normal',
  `contact_name` VARCHAR(255) NOT NULL,
  `contact_phone` VARCHAR(20) NOT NULL,
  `contact_email` VARCHAR(255) DEFAULT NULL,
  `desired_delivery_date` DATE DEFAULT NULL,
  `needs_consultation` TINYINT(1) NOT NULL DEFAULT 1,
  `needs_design` TINYINT(1) NOT NULL DEFAULT 0,
  `needs_installation` TINYINT(1) NOT NULL DEFAULT 0,
  `needs_permit_followup` TINYINT(1) NOT NULL DEFAULT 0,
  `description` TEXT DEFAULT NULL,
  `admin_notes` TEXT DEFAULT NULL,
  `meeting_scheduled_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE SET NULL,
  INDEX `service_requests_status_created_idx` (`status`, `created_at`),
  INDEX `service_requests_org_status_idx` (`organization_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
