/**
 * چاپخانه — PHP backend development runner.
 *
 * Serves the plain-PHP API in ../ (php-backend) through PHP compiled to
 * WebAssembly (@php-wasm/node) so the full stack runs without installing PHP
 * or MySQL. The PHP code itself is unchanged: in production the very same
 * endpoints run on native PHP with MySQL.
 *
 *   npm run backend        # from the repository root
 *
 * Environment:
 *   PHP_BACKEND_PORT  (default 8080)
 *   PHP_BACKEND_HOST  (default 0.0.0.0)
 *
 * Behaviour:
 *   - On the first run, installs the runner's own npm dependencies here.
 *   - Creates ../.env (DB_DRIVER=sqlite + dev admin) when it does not exist,
 *     then every request keeps using the real DB flow in config/database.php.
 *   - Applies migrations/sqlite/schema.sql and seeds the first admin through
 *     scripts/bootstrap.php before accepting traffic.
 */
import { spawn, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'node:http';

const runnerDir = dirname(fileURLToPath(import.meta.url));
const backendDir = dirname(runnerDir);
const port = Number(process.env.PHP_BACKEND_PORT || 8080);
const host = process.env.PHP_BACKEND_HOST || '0.0.0.0';

const PHP_VFS_ROOT = '/backend';
const DOCROOT = `${PHP_VFS_ROOT}/public`;

function log(...args) {
  console.log('[php-wasm-runner]', ...args);
}

async function importRunnerDeps() {
  try {
    const universal = await import('@php-wasm/universal');
    const nodeModule = await import('@php-wasm/node');
    return { universal, nodeModule };
  } catch (error) {
    return null;
  }
}

async function ensureDeps() {
  let deps = await importRunnerDeps();
  if (deps) return deps;
  if (process.env.CHAPKHANE_RUNNER_BOOTSTRAPPED === '1') {
    throw new Error(
      'Runner dependencies are unavailable even after npm install. ' +
        'Try manually: cd php-backend/wasm-runner && npm install'
    );
  }
  log('first run: installing runner dependencies (PHP runtime as WebAssembly)…');
  // On Windows npm is an npm.cmd shim; bare `npm` is not executable without a
  // shell, which used to fail with "exit null" (ENOENT/EINVAL).
  const isWindows = process.platform === 'win32';
  const install = spawnSync(
    isWindows ? 'npm.cmd' : 'npm',
    ['install', '--no-audit', '--no-fund', '--loglevel=error'],
    {
      cwd: runnerDir,
      stdio: 'inherit',
      shell: isWindows,
      env: { ...process.env, npm_config_loglevel: 'error' },
    }
  );
  if (install.error) {
    throw new Error(
      `npm install for wasm-runner could not start: ${install.error.message}. ` +
        'Install manually: cd php-backend/wasm-runner && npm install'
    );
  }
  if (install.status !== 0) {
    throw new Error(
      `npm install for wasm-runner failed (exit ${install.status ?? install.signal}). ` +
        'Try manually: cd php-backend/wasm-runner && npm install'
    );
  }
  // Re-exec with a fresh module cache so the newly installed packages resolve.
  const child = spawn(process.execPath, [fileURLToPath(import.meta.url), ...process.argv.slice(2)], {
    stdio: 'inherit',
    env: { ...process.env, CHAPKHANE_RUNNER_BOOTSTRAPPED: '1' },
  });
  child.on('exit', (code) => process.exit(code ?? 0));
  return new Promise(() => {});
}

function ensureBackendEnv() {
  const envPath = join(backendDir, '.env');
  if (existsSync(envPath)) {
    log(`using existing ${envPath}`);
    return;
  }
  const sqlitePath = `${PHP_VFS_ROOT}/.data/chapkhane.sqlite`;
  writeFileSync(
    envPath,
    [
      '# Generated by php-backend/wasm-runner for local development.',
      '# Production: switch DB_DRIVER to mysql and fill the MySQL credentials.',
      'DB_DRIVER=sqlite',
      `SQLITE_PATH=${sqlitePath}`,
      'ADMIN_NAME=مدیر چاپخانه',
      'ADMIN_PHONE=09120000000',
      'ADMIN_PASSWORD=admin123456',
      '',
    ].join('\n'),
    { encoding: 'utf8' }
  );
  log(`created ${envPath} (sqlite + dev admin 09120000000 / admin123456)`);
}

async function runBootstrap(php) {
  const result = await php.runStream({
    scriptPath: `${PHP_VFS_ROOT}/scripts/bootstrap.php`,
  });
  const stdout = await result.stdoutText;
  const stderr = await result.stderrText;
  if (stdout.trim()) log(`bootstrap: ${stdout.trim()}`);
  if (stderr.trim()) console.error('[php-wasm-runner] bootstrap stderr:', stderr.trim());
}

/**
 * `npm run backend:admin -- <phone> <password> [name]`
 * Creates or resets the admin account without starting the server.
 */
async function runSetAdminTool(args) {
  const [phone, password, name] = args;
  if (!phone || !password) {
    console.error(
      'کاربرد: npm run backend:admin -- <موبایل> <رمز جدید> [نام]\n' +
        'مثال:   npm run backend:admin -- 09120000000 admin123456'
    );
    process.exit(1);
  }

  const { universal, nodeModule } = await ensureDeps();
  if (!universal || !nodeModule) return;
  const { PHP } = universal;
  const { loadNodeRuntime, createNodeFsMountHandler } = nodeModule;

  mkdirSync(join(backendDir, '.data'), { recursive: true });
  ensureBackendEnv();

  const php = new PHP(
    await loadNodeRuntime('8.3', {
      emscriptenOptions: {
        processId: 1,
        ENV: {
          ADMIN_TOOL_PHONE: phone,
          ADMIN_TOOL_PASSWORD: password,
          ADMIN_TOOL_NAME: name ?? '',
        },
      },
    })
  );
  await php.mount(PHP_VFS_ROOT, createNodeFsMountHandler(backendDir));

  const result = await php.runStream({
    scriptPath: `${PHP_VFS_ROOT}/scripts/set-admin-password.php`,
  });
  const stdout = (await result.stdoutText).trim();
  const stderr = (await result.stderrText).trim();
  if (stdout) console.log(stdout);
  if (stderr) console.error(stderr);

  const ok = /"ok"\s*:\s*true/.test(stdout);
  if (ok) {
    console.log(`[php-wasm-runner] مدیر آماده است — ورود با موبایل ${phone} و رمز تعیین‌شده.`);
  }
  process.exit(ok ? 0 : 1);
}

async function main() {
  const setAdminFlag = process.argv.indexOf('--set-admin');
  if (setAdminFlag !== -1) {
    await runSetAdminTool(process.argv.slice(setAdminFlag + 1));
    return;
  }

  const { universal, nodeModule } = await ensureDeps();
  if (!universal || !nodeModule) return; // re-exec in progress
  const { PHP, PHPRequestHandler, setPhpIniEntries } = universal;
  const { loadNodeRuntime, createNodeFsMountHandler } = nodeModule;

  mkdirSync(join(backendDir, '.data'), { recursive: true });
  ensureBackendEnv();

  log('loading PHP 8.3 runtime (WebAssembly)…');
  const php = new PHP(
    await loadNodeRuntime('8.3', {
      emscriptenOptions: { processId: 1 },
    })
  );
  await php.mount(PHP_VFS_ROOT, createNodeFsMountHandler(backendDir));
  await php.chdir(DOCROOT);
  // Keep JSON responses clean: PHP warnings go to stderr (logged per request)
  // instead of being printed into the response body.
  await setPhpIniEntries(php, {
    display_errors: 'stderr',
    log_errors: '1',
    error_reporting: 'E_ALL',
  });

  await runBootstrap(php);

  const handler = new PHPRequestHandler({
    php,
    documentRoot: DOCROOT,
    absoluteUrl: `http://localhost:${port}`,
    cookieStore: false,
    // Front-controller pattern: public/ only contains index.php, so every
    // path is handled by it (mirrors `php -S host:port public/index.php`).
    rewriteRules: [
      { match: /^\/(?!index\.php(?:\?|$)).*?((?:\?).*)?$/, replacement: '/index.php$1' },
    ],
  });

  const server = createServer(async (req, res) => {
    const started = Date.now();
    try {
      const bodyChunks = [];
      for await (const chunk of req) bodyChunks.push(chunk);
      const body = Buffer.concat(bodyChunks);

      const headers = {};
      for (const [key, value] of Object.entries(req.headers)) {
        if (typeof value === 'string') headers[key] = value;
        else if (Array.isArray(value)) headers[key] = value.join(', ');
      }
      delete headers['connection'];
      delete headers['content-length'];

      const response = await handler.request({
        method: req.method,
        url: req.url || '/',
        headers,
        ...(body.length ? { body: new Uint8Array(body) } : {}),
      });

      const responseHeaders = { ...response.headers };
      const status = response.httpStatusCode || 200;
      res.writeHead(status, responseHeaders);
      res.end(Buffer.from(response.bytes));
      const phpErrors = (response.errors || '').trim();
      if (phpErrors) console.error(`[php-wasm-runner] php stderr for ${req.method} ${req.url}:`, phpErrors);
      log(`${req.method} ${req.url} → ${status} (${Date.now() - started}ms)`);
    } catch (error) {
      console.error('[php-wasm-runner] request failed:', error);
      if (!res.headersSent) {
        res.writeHead(502, { 'content-type': 'application/json; charset=utf-8' });
      }
      res.end(JSON.stringify({ message: 'wasm backend error' }));
    }
  });

  server.listen(port, host, () => {
    log(`PHP API (WASM) listening on http://${host}:${port}`);
    log(`health check: http://localhost:${port}/health`);
  });

  const shutdown = () => {
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 1500).unref();
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch((error) => {
  console.error('[php-wasm-runner] fatal:', error);
  process.exit(1);
});
